name: projet2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # Mise à jour à la version 1.0.0
  cloud_firestore: ^5.0.0 # Mise à jour à la version 1.0.0
  firebase_core: ^3.0.0 # Mise à jour à la version 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Mise à jour à la version 4.0.0

flutter:
  uses-material-design: true
