name: pinterest_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpeg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/image6.jpg
    - assets/image7.jpg
    - assets/image8.jpg