name: phoneauth_firebase
description: Un nouveau projet Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  country_picker: ^2.0.20
  firebase_core: ^3.9.2
  firebase_auth: ^4.9.1
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.3.2
  shared_preferences: ^2.1.1
  provider: ^6.1.6
  pinput: ^2.3.0
  image_picker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
