name: appli_devoir
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  animate_do: ^3.1.2
  shimmer: ^2.0.0
  # flashy_tab_bar: ^0.0.3
  flutter_staggered_grid_view: ^0.4.0
  iconsax: ^0.0.8
  dio: ^4.0.0
  url_launcher: ^6.0.12
  concentric_transition: ^1.0.1
  odometer: ^2.1.0
  vertical_card_pager: ^1.5.0
  loading_indicator: ^3.0.2
  flutter_youtube_view: ^2.0.2
  flutter_verification_code: ^1.1.0
  liquid_swipe: ^2.1.0
  intl_phone_number_input: ^0.7.0+2
  elastic_drawer: ^2.0.1
  bouncing_widget: ^2.0.0
  bottom_navy_bar: ^6.0.0
  salomon_bottom_bar: ^3.1.0
  avatar_glow: ^2.0.2
  carousel_slider: ^4.0.0
  google_fonts: ^2.1.0
  fl_chart: ^0.40.2
  country_picker: ^2.0.18


  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  pinput: ^2.2.16
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png
    - assets/images/
    - assets/images/plant.jpeg
    - assets/images/akatsuki.png
    - assets/akatsuki.png
    - assets/Note.webp

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
