// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ8MqDo_ksExvfA0q-XCvgrf8OdZKX-JE',
    appId: '1:758398808621:web:96f5889e8df7fdb5c3bea4',
    messagingSenderId: '758398808621',
    projectId: 'identity-validation-df03a',
    authDomain: 'identity-validation-df03a.firebaseapp.com',
    storageBucket: 'identity-validation-df03a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfRZNqwfqTP9oaHDtLSjoz3Kh2cgsZ4p0',
    appId: '1:758398808621:android:715a5374b2b70eeec3bea4',
    messagingSenderId: '758398808621',
    projectId: 'identity-validation-df03a',
    storageBucket: 'identity-validation-df03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOPG912pG2TABprraO1lp_XZkQw1IZ_VA',
    appId: '1:758398808621:ios:ae20f5988ebaf46fc3bea4',
    messagingSenderId: '758398808621',
    projectId: 'identity-validation-df03a',
    storageBucket: 'identity-validation-df03a.appspot.com',
    iosBundleId: 'com.example.identityValidation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOPG912pG2TABprraO1lp_XZkQw1IZ_VA',
    appId: '1:758398808621:ios:ae20f5988ebaf46fc3bea4',
    messagingSenderId: '758398808621',
    projectId: 'identity-validation-df03a',
    storageBucket: 'identity-validation-df03a.appspot.com',
    iosBundleId: 'com.example.identityValidation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ8MqDo_ksExvfA0q-XCvgrf8OdZKX-JE',
    appId: '1:758398808621:web:d223a52e396453eac3bea4',
    messagingSenderId: '758398808621',
    projectId: 'identity-validation-df03a',
    authDomain: 'identity-validation-df03a.firebaseapp.com',
    storageBucket: 'identity-validation-df03a.appspot.com',
  );
}
